name: release
on: 
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build
      - name: Upload artifact to GitHub Releases
        run: |
            version="v$(node -p "require('./package.json').version")"
            sha256sum ./dist/resources/extension-trivy.tar > extension-trivy_checksums.txt
            gh release create -F CHANGELOG.md --verify-tag $version ./dist/resources/extension-trivy.tar ./extension-trivy_checksums.txt
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}